#!/usr/bin/env python3
"""Regenerate the shim table and callback trampolines; run from the repo root."""
from pathlib import Path
import json

EARLY = [
    ('kernel32.dll', n) for n in ('WerSetFlags', 'WerGetFlags', 'GetErrorMode',
    'CreateWaitableTimerExW', 'RaiseFailFastException', 'GetQueuedCompletionStatusEx',
    'LoadLibraryExW', 'GetProcAddress')
] + [('bcryptprimitives.dll', 'ProcessPrng')]
LATE = [
    ('kernel32.dll', 'CancelIoEx', 2),
    ('kernel32.dll', 'GetFileInformationByHandleEx', 4),
    ('kernel32.dll', 'SetFileInformationByHandle', 4),
    ('kernel32.dll', 'InitializeProcThreadAttributeList', 4),
    ('kernel32.dll', 'UpdateProcThreadAttribute', 7),
    ('kernel32.dll', 'DeleteProcThreadAttributeList', 1),
    ('ws2_32.dll', 'WSASocketW', 6),
    ('kernel32.dll', 'CreateEventExW', 4),
    ('kernel32.dll', 'CreateProcessW', 10),
    ('ntdll.dll', 'NtCreateFile', 11),
    ('kernel32.dll', 'GetVolumeInformationByHandleW', 8),
]
OWNS = [('kernel32.dll', n) for n in ('SetErrorMode', 'TerminateProcess',
    'GetQueuedCompletionStatus', 'CancelIo', 'GetSystemDirectoryW', 'SetLastError', 'GetTickCount')
] + [('advapi32.dll', 'SystemFunction036')]
HOOKS = {'LoadLibraryExW', 'GetProcAddress'}
MISSING_DLLS = ['bcryptprimitives.dll']
OVERRIDES = ['WSASocketW', 'CreateProcessW', 'NtCreateFile']
# Functions XP lacks that have no polyfill: (dll, name, argc, return value, last error).
# They exist so that LazyProc.Addr() finds *something*: an unresolved LazyProc panics
# (syscall.(*LazyProc).mustFind), which is how the first real XP run died. A stub turns
# that panic into the ordinary failure the caller already handles. Return values follow
# each function's own failure convention; the last error is ERROR_CALL_NOT_IMPLEMENTED
# (120) where one applies. The hooks still prefer the real export, so a stub is only ever
# reached where the function is genuinely absent.
STUBS = [
    ('kernel32.dll', 'GetFinalPathNameByHandleW', 4, 0, 120),          # DWORD, 0 = failure
    ('kernel32.dll', 'CreateSymbolicLinkW', 3, 0, 120),                # BOOLEAN
    ('kernel32.dll', 'ReOpenFile', 4, -1, 120),                        # INVALID_HANDLE_VALUE
    ('kernel32.dll', 'QueryFullProcessImageNameW', 4, 0, 120),         # BOOL
    ('kernel32.dll', 'GetCurrentConsoleFontEx', 3, 0, 120),            # BOOL
    ('kernel32.dll', 'FindFirstStreamW', 4, -1, 120),                  # INVALID_HANDLE_VALUE
    ('kernel32.dll', 'FindNextStreamW', 2, 0, 18),                     # BOOL, ERROR_NO_MORE_FILES
    ('kernel32.dll', 'CreatePseudoConsole', 5, 0x80004001, 0),         # HRESULT E_NOTIMPL
    ('kernel32.dll', 'ResizePseudoConsole', 2, 0x80004001, 0),
    ('kernel32.dll', 'ClosePseudoConsole', 1, 0, 0),                   # void
    ('kernel32.dll', 'GetTickCount64', 0, 0, 0),                       # see asm: real one below
    ('advapi32.dll', 'RegLoadMUIStringW', 7, 120, 0),                  # LSTATUS returned directly
    ('ws2_32.dll', 'WSAPoll', 3, -1, 0),                               # SOCKET_ERROR; WSA error set in asm
    ('dwmapi.dll', 'DwmSetWindowAttribute', 4, 0x80004001, 0),         # HRESULT E_NOTIMPL
    ('user32.dll', 'GetDpiForWindow', 1, 96, 0),                       # USER_DEFAULT_SCREEN_DPI
    ('user32.dll', 'SetProcessDpiAwarenessContext', 1, 0, 120),        # BOOL
]
BEGIN = '// --- generated by gen_table.py: begin ---'
END = '// --- generated by gen_table.py: end ---'
TRAMP_BEGIN = '// --- generated trampolines: begin ---'
TRAMP_END = '// --- generated trampolines: end ---'


def sym(s):
    return 'go2xp_s_' + s.replace('.', '_')


def main():
    entries = [(d, f, '·xp_' + f + '(SB)', 'go2xp_' + f + '(SB)' if f in HOOKS else '0')
               for d, f in EARLY + [(d, f) for d, f, _ in LATE]]
    entries += [(d, f, '·xp_' + f + '(SB)', '0') for d, f, _, _, _ in STUBS]
    entries += [(d, f, '0', 'go2xp_' + f + '(SB)') for d, f in OWNS]
    data = [BEGIN, 'DATA go2xp_table+0(SB)/8, $"GO2XPTBL"',
            'DATA go2xp_table+8(SB)/4, $1', f'DATA go2xp_table+12(SB)/4, ${len(entries)}']
    strings = set(MISSING_DLLS + OVERRIDES)
    for i, (dll, fn, poly, own) in enumerate(entries):
        strings.update((dll, fn))
        data.append(f'// {dll}!{fn}')
        values = (sym(dll) + '(SB)', sym(fn) + '(SB)', poly, own)
        for j, value in enumerate(values):
            data.append(f'DATA go2xp_table+{16 + i * 16 + j * 4}(SB)/4, ${value}')
    data.append(f'GLOBL go2xp_table(SB), NOPTR, ${16 + 16 * len(entries)}')
    for name, items in [('go2xp_missing_dlls', MISSING_DLLS), ('go2xp_overrides', OVERRIDES)]:
        for i, item in enumerate(items):
            data.append(f'DATA {name}+{i * 4}(SB)/4, ${sym(item)}(SB)')
        data += [f'DATA {name}+{len(items) * 4}(SB)/4, $0',
                 f'GLOBL {name}(SB), RODATA|NOPTR, ${(len(items) + 1) * 4}']
    for value in sorted(strings):
        raw = value + '\0'
        raw += '\0' * (-len(raw) % 8)
        for i in range(0, len(raw), 8):
            literal = json.dumps(raw[i:i+8]).replace('\\u0000', '\\x00')
            data.append(f'DATA {sym(value)}+{i}(SB)/8, ${literal}')
        data.append(f'GLOBL {sym(value)}(SB), RODATA|NOPTR, ${len(raw)}')
    data.append(END)
    tramp = [TRAMP_BEGIN]
    for _, fn, argc in LATE:
        tramp.append(f'''// {fn}: stdcall callback, available after shim.init.
TEXT ·xp_{fn}(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cb{fn}(SB), AX
	TESTL	AX, AX
	JZ	t_{fn}_early
	JMP	AX
t_{fn}_early:
	XORL	AX, AX
	STDRET({argc * 4})
''')
    for dll, fn, argc, ret, err in STUBS:
        if fn == 'GetTickCount64':
            continue  # hand-written: needs a 64-bit result
        body = ''
        if err:
            body += f'\tSUBL\t$4, SP\n\tMOVL\t${err}, 0(SP)\n\tMOVL\tgo2xp_SetLastError(SB), AX\n\tCALL\tAX\n'
        if dll == 'ws2_32.dll':
            # WSAEOPNOTSUPP via WSASetLastError, which is only known once ws2_32 has been
            # loaded by the socket wrapper; skip it if not.
            body += (f'\tMOVL\t·wsaSetLastError(SB), AX\n\tTESTL\tAX, AX\n\tJZ\ts_{fn}_ret\n'
                     f'\tSUBL\t$4, SP\n\tMOVL\t$10045, 0(SP)\n\tCALL\tAX\ns_{fn}_ret:\n')
        tramp.append(f'''// {dll}!{fn}: absent on the target, no polyfill. Returns {ret}{', last error ' + str(err) if err else ''}
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_{fn}(SB), NOSPLIT|NOFRAME, $0-0
{body}\tMOVL\t${ret}, AX
\tSTDRET({argc * 4})
''')
    tramp.append(TRAMP_END)
    path = Path('shim/shim_windows_386.s')
    s = path.read_text()
    for begin, end, replacement in [(BEGIN, END, data), (TRAMP_BEGIN, TRAMP_END, tramp)]:
        a, b = s.index(begin), s.index(end) + len(end)
        s = s[:a] + '\n'.join(replacement) + s[b:]
    path.write_text(s)


if __name__ == '__main__':
    main()
