#!/usr/bin/env python3
"""Regenerate the shim table and callback trampolines; run from the repo root."""
from pathlib import Path
import json

EARLY = [
    ('kernel32.dll', n) for n in ('WerSetFlags', 'WerGetFlags', 'GetErrorMode',
    'CreateWaitableTimerExW', 'RaiseFailFastException', 'GetQueuedCompletionStatusEx',
    'LoadLibraryExW', 'GetProcAddress')
] + [('bcryptprimitives.dll', 'ProcessPrng')]
LATE = [
    ('kernel32.dll', 'CancelIoEx', 2),
    ('kernel32.dll', 'GetFileInformationByHandleEx', 4),
    ('kernel32.dll', 'SetFileInformationByHandle', 4),
    ('kernel32.dll', 'InitializeProcThreadAttributeList', 4),
    ('kernel32.dll', 'UpdateProcThreadAttribute', 7),
    ('kernel32.dll', 'DeleteProcThreadAttributeList', 1),
    ('ws2_32.dll', 'WSASocketW', 6),
    ('kernel32.dll', 'CreateEventExW', 4),
    ('kernel32.dll', 'CreateProcessW', 10),
    ('ntdll.dll', 'NtCreateFile', 11),
]
OWNS = [('kernel32.dll', n) for n in ('SetErrorMode', 'TerminateProcess',
    'GetQueuedCompletionStatus', 'CancelIo', 'GetSystemDirectoryW', 'SetLastError')
] + [('advapi32.dll', 'SystemFunction036')]
HOOKS = {'LoadLibraryExW', 'GetProcAddress'}
MISSING_DLLS = ['bcryptprimitives.dll']
OVERRIDES = ['WSASocketW', 'CreateProcessW', 'NtCreateFile']
BEGIN = '// --- generated by gen_table.py: begin ---'
END = '// --- generated by gen_table.py: end ---'
TRAMP_BEGIN = '// --- generated trampolines: begin ---'
TRAMP_END = '// --- generated trampolines: end ---'


def sym(s):
    return 'go2xp_s_' + s.replace('.', '_')


def main():
    entries = [(d, f, '·xp_' + f + '(SB)', 'go2xp_' + f + '(SB)' if f in HOOKS else '0')
               for d, f in EARLY + [(d, f) for d, f, _ in LATE]]
    entries += [(d, f, '0', 'go2xp_' + f + '(SB)') for d, f in OWNS]
    data = [BEGIN, 'DATA go2xp_table+0(SB)/8, $"GO2XPTBL"',
            'DATA go2xp_table+8(SB)/4, $1', f'DATA go2xp_table+12(SB)/4, ${len(entries)}']
    strings = set(MISSING_DLLS + OVERRIDES)
    for i, (dll, fn, poly, own) in enumerate(entries):
        strings.update((dll, fn))
        data.append(f'// {dll}!{fn}')
        values = (sym(dll) + '(SB)', sym(fn) + '(SB)', poly, own)
        for j, value in enumerate(values):
            data.append(f'DATA go2xp_table+{16 + i * 16 + j * 4}(SB)/4, ${value}')
    data.append(f'GLOBL go2xp_table(SB), NOPTR, ${16 + 16 * len(entries)}')
    for name, items in [('go2xp_missing_dlls', MISSING_DLLS), ('go2xp_overrides', OVERRIDES)]:
        for i, item in enumerate(items):
            data.append(f'DATA {name}+{i * 4}(SB)/4, ${sym(item)}(SB)')
        data += [f'DATA {name}+{len(items) * 4}(SB)/4, $0',
                 f'GLOBL {name}(SB), RODATA|NOPTR, ${(len(items) + 1) * 4}']
    for value in sorted(strings):
        raw = value + '\0'
        raw += '\0' * (-len(raw) % 8)
        for i in range(0, len(raw), 8):
            literal = json.dumps(raw[i:i+8]).replace('\\u0000', '\\x00')
            data.append(f'DATA {sym(value)}+{i}(SB)/8, ${literal}')
        data.append(f'GLOBL {sym(value)}(SB), RODATA|NOPTR, ${len(raw)}')
    data.append(END)
    tramp = [TRAMP_BEGIN]
    for _, fn, argc in LATE:
        tramp.append(f'''// {fn}: stdcall callback, available after shim.init.
TEXT ·xp_{fn}(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cb{fn}(SB), AX
	TESTL	AX, AX
	JZ	t_{fn}_early
	JMP	AX
t_{fn}_early:
	XORL	AX, AX
	STDRET({argc * 4})
''')
    tramp.append(TRAMP_END)
    path = Path('shim/shim_windows_386.s')
    s = path.read_text()
    for begin, end, replacement in [(BEGIN, END, data), (TRAMP_BEGIN, TRAMP_END, tramp)]:
        a, b = s.index(begin), s.index(end) + len(end)
        s = s[:a] + '\n'.join(replacement) + s[b:]
    path.write_text(s)


if __name__ == '__main__':
    main()
