#include "textflag.h"

// The Go 386 assembler has no "RET $imm"; encode "ret imm16" by hand.
#define STDRET(n) BYTE $0xC2; WORD $n

// A handle that xp_LoadLibraryExW returns for a DLL that does not exist on the target.
// Module handles are image bases and therefore 64K-aligned, so this value can never
// collide with a real one.
#define SENTINEL $0x476F3258

// GO2XPTBL, the contract between this package and cmd/go2xp:
//   +0  magic   "GO2XPTBL"
//   +8  version u32 = 1
//   +12 count   u32
//   +16 entries, 16 bytes each:
//        +0  VA of the DLL name  (C string, lowercase)
//        +4  VA of the function name (C string)
//        +8  VA of the polyfill, or 0 when the entry only marks an own slot
//        +12 VA of the shim's own IAT slot, or 0
//
// An entry with a polyfill tells the patcher: if this function is missing on the target
// OS, point its IAT slot here. An entry with an own slot tells it: this slot belongs to
// the shim, never redirect it. An entry may carry both, which is what the two hooks do.
// Every own import needs an entry, otherwise the linker drops the slot as dead code.
//
// Polyfills are __stdcall: arguments on the stack, callee pops them (STDRET), EAX holds
// the result, EBX/ESI/EDI/EBP must be preserved. The early ones run during
// runtime.osinit, before the Go runtime exists, so they must not touch g, TLS or anything
// else Go-specific, and may only call out through the shim's own import slots. The late
// ones are trampolines into Go (see cb* in shim_windows_386.go).
//
// Note on stack discipline: the assembler rejects a function whose PUSH and POP counts
// differ, and stdcall argument pushes always break that (the callee pops them), so
// arguments are written with SUBL/MOVL instead of PUSHL.

// --- generated by gen_table.py: begin ---
DATA go2xp_table+0(SB)/8, $"GO2XPTBL"
DATA go2xp_table+8(SB)/4, $1
DATA go2xp_table+12(SB)/4, $44
// kernel32.dll!WerSetFlags
DATA go2xp_table+16(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+20(SB)/4, $go2xp_s_WerSetFlags(SB)
DATA go2xp_table+24(SB)/4, $·xp_WerSetFlags(SB)
DATA go2xp_table+28(SB)/4, $0
// kernel32.dll!WerGetFlags
DATA go2xp_table+32(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+36(SB)/4, $go2xp_s_WerGetFlags(SB)
DATA go2xp_table+40(SB)/4, $·xp_WerGetFlags(SB)
DATA go2xp_table+44(SB)/4, $0
// kernel32.dll!GetErrorMode
DATA go2xp_table+48(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+52(SB)/4, $go2xp_s_GetErrorMode(SB)
DATA go2xp_table+56(SB)/4, $·xp_GetErrorMode(SB)
DATA go2xp_table+60(SB)/4, $0
// kernel32.dll!CreateWaitableTimerExW
DATA go2xp_table+64(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+68(SB)/4, $go2xp_s_CreateWaitableTimerExW(SB)
DATA go2xp_table+72(SB)/4, $·xp_CreateWaitableTimerExW(SB)
DATA go2xp_table+76(SB)/4, $0
// kernel32.dll!RaiseFailFastException
DATA go2xp_table+80(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+84(SB)/4, $go2xp_s_RaiseFailFastException(SB)
DATA go2xp_table+88(SB)/4, $·xp_RaiseFailFastException(SB)
DATA go2xp_table+92(SB)/4, $0
// kernel32.dll!GetQueuedCompletionStatusEx
DATA go2xp_table+96(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+100(SB)/4, $go2xp_s_GetQueuedCompletionStatusEx(SB)
DATA go2xp_table+104(SB)/4, $·xp_GetQueuedCompletionStatusEx(SB)
DATA go2xp_table+108(SB)/4, $0
// kernel32.dll!LoadLibraryExW
DATA go2xp_table+112(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+116(SB)/4, $go2xp_s_LoadLibraryExW(SB)
DATA go2xp_table+120(SB)/4, $·xp_LoadLibraryExW(SB)
DATA go2xp_table+124(SB)/4, $go2xp_LoadLibraryExW(SB)
// kernel32.dll!GetProcAddress
DATA go2xp_table+128(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+132(SB)/4, $go2xp_s_GetProcAddress(SB)
DATA go2xp_table+136(SB)/4, $·xp_GetProcAddress(SB)
DATA go2xp_table+140(SB)/4, $go2xp_GetProcAddress(SB)
// bcryptprimitives.dll!ProcessPrng
DATA go2xp_table+144(SB)/4, $go2xp_s_bcryptprimitives_dll(SB)
DATA go2xp_table+148(SB)/4, $go2xp_s_ProcessPrng(SB)
DATA go2xp_table+152(SB)/4, $·xp_ProcessPrng(SB)
DATA go2xp_table+156(SB)/4, $0
// kernel32.dll!CancelIoEx
DATA go2xp_table+160(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+164(SB)/4, $go2xp_s_CancelIoEx(SB)
DATA go2xp_table+168(SB)/4, $·xp_CancelIoEx(SB)
DATA go2xp_table+172(SB)/4, $0
// kernel32.dll!GetFileInformationByHandleEx
DATA go2xp_table+176(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+180(SB)/4, $go2xp_s_GetFileInformationByHandleEx(SB)
DATA go2xp_table+184(SB)/4, $·xp_GetFileInformationByHandleEx(SB)
DATA go2xp_table+188(SB)/4, $0
// kernel32.dll!SetFileInformationByHandle
DATA go2xp_table+192(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+196(SB)/4, $go2xp_s_SetFileInformationByHandle(SB)
DATA go2xp_table+200(SB)/4, $·xp_SetFileInformationByHandle(SB)
DATA go2xp_table+204(SB)/4, $0
// kernel32.dll!InitializeProcThreadAttributeList
DATA go2xp_table+208(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+212(SB)/4, $go2xp_s_InitializeProcThreadAttributeList(SB)
DATA go2xp_table+216(SB)/4, $·xp_InitializeProcThreadAttributeList(SB)
DATA go2xp_table+220(SB)/4, $0
// kernel32.dll!UpdateProcThreadAttribute
DATA go2xp_table+224(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+228(SB)/4, $go2xp_s_UpdateProcThreadAttribute(SB)
DATA go2xp_table+232(SB)/4, $·xp_UpdateProcThreadAttribute(SB)
DATA go2xp_table+236(SB)/4, $0
// kernel32.dll!DeleteProcThreadAttributeList
DATA go2xp_table+240(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+244(SB)/4, $go2xp_s_DeleteProcThreadAttributeList(SB)
DATA go2xp_table+248(SB)/4, $·xp_DeleteProcThreadAttributeList(SB)
DATA go2xp_table+252(SB)/4, $0
// ws2_32.dll!WSASocketW
DATA go2xp_table+256(SB)/4, $go2xp_s_ws2_32_dll(SB)
DATA go2xp_table+260(SB)/4, $go2xp_s_WSASocketW(SB)
DATA go2xp_table+264(SB)/4, $·xp_WSASocketW(SB)
DATA go2xp_table+268(SB)/4, $0
// kernel32.dll!CreateEventExW
DATA go2xp_table+272(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+276(SB)/4, $go2xp_s_CreateEventExW(SB)
DATA go2xp_table+280(SB)/4, $·xp_CreateEventExW(SB)
DATA go2xp_table+284(SB)/4, $0
// kernel32.dll!CreateProcessW
DATA go2xp_table+288(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+292(SB)/4, $go2xp_s_CreateProcessW(SB)
DATA go2xp_table+296(SB)/4, $·xp_CreateProcessW(SB)
DATA go2xp_table+300(SB)/4, $0
// ntdll.dll!NtCreateFile
DATA go2xp_table+304(SB)/4, $go2xp_s_ntdll_dll(SB)
DATA go2xp_table+308(SB)/4, $go2xp_s_NtCreateFile(SB)
DATA go2xp_table+312(SB)/4, $·xp_NtCreateFile(SB)
DATA go2xp_table+316(SB)/4, $0
// kernel32.dll!GetVolumeInformationByHandleW
DATA go2xp_table+320(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+324(SB)/4, $go2xp_s_GetVolumeInformationByHandleW(SB)
DATA go2xp_table+328(SB)/4, $·xp_GetVolumeInformationByHandleW(SB)
DATA go2xp_table+332(SB)/4, $0
// kernel32.dll!GetFinalPathNameByHandleW
DATA go2xp_table+336(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+340(SB)/4, $go2xp_s_GetFinalPathNameByHandleW(SB)
DATA go2xp_table+344(SB)/4, $·xp_GetFinalPathNameByHandleW(SB)
DATA go2xp_table+348(SB)/4, $0
// kernel32.dll!CreateSymbolicLinkW
DATA go2xp_table+352(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+356(SB)/4, $go2xp_s_CreateSymbolicLinkW(SB)
DATA go2xp_table+360(SB)/4, $·xp_CreateSymbolicLinkW(SB)
DATA go2xp_table+364(SB)/4, $0
// kernel32.dll!ReOpenFile
DATA go2xp_table+368(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+372(SB)/4, $go2xp_s_ReOpenFile(SB)
DATA go2xp_table+376(SB)/4, $·xp_ReOpenFile(SB)
DATA go2xp_table+380(SB)/4, $0
// kernel32.dll!QueryFullProcessImageNameW
DATA go2xp_table+384(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+388(SB)/4, $go2xp_s_QueryFullProcessImageNameW(SB)
DATA go2xp_table+392(SB)/4, $·xp_QueryFullProcessImageNameW(SB)
DATA go2xp_table+396(SB)/4, $0
// kernel32.dll!GetCurrentConsoleFontEx
DATA go2xp_table+400(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+404(SB)/4, $go2xp_s_GetCurrentConsoleFontEx(SB)
DATA go2xp_table+408(SB)/4, $·xp_GetCurrentConsoleFontEx(SB)
DATA go2xp_table+412(SB)/4, $0
// kernel32.dll!FindFirstStreamW
DATA go2xp_table+416(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+420(SB)/4, $go2xp_s_FindFirstStreamW(SB)
DATA go2xp_table+424(SB)/4, $·xp_FindFirstStreamW(SB)
DATA go2xp_table+428(SB)/4, $0
// kernel32.dll!FindNextStreamW
DATA go2xp_table+432(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+436(SB)/4, $go2xp_s_FindNextStreamW(SB)
DATA go2xp_table+440(SB)/4, $·xp_FindNextStreamW(SB)
DATA go2xp_table+444(SB)/4, $0
// kernel32.dll!CreatePseudoConsole
DATA go2xp_table+448(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+452(SB)/4, $go2xp_s_CreatePseudoConsole(SB)
DATA go2xp_table+456(SB)/4, $·xp_CreatePseudoConsole(SB)
DATA go2xp_table+460(SB)/4, $0
// kernel32.dll!ResizePseudoConsole
DATA go2xp_table+464(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+468(SB)/4, $go2xp_s_ResizePseudoConsole(SB)
DATA go2xp_table+472(SB)/4, $·xp_ResizePseudoConsole(SB)
DATA go2xp_table+476(SB)/4, $0
// kernel32.dll!ClosePseudoConsole
DATA go2xp_table+480(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+484(SB)/4, $go2xp_s_ClosePseudoConsole(SB)
DATA go2xp_table+488(SB)/4, $·xp_ClosePseudoConsole(SB)
DATA go2xp_table+492(SB)/4, $0
// kernel32.dll!GetTickCount64
DATA go2xp_table+496(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+500(SB)/4, $go2xp_s_GetTickCount64(SB)
DATA go2xp_table+504(SB)/4, $·xp_GetTickCount64(SB)
DATA go2xp_table+508(SB)/4, $0
// advapi32.dll!RegLoadMUIStringW
DATA go2xp_table+512(SB)/4, $go2xp_s_advapi32_dll(SB)
DATA go2xp_table+516(SB)/4, $go2xp_s_RegLoadMUIStringW(SB)
DATA go2xp_table+520(SB)/4, $·xp_RegLoadMUIStringW(SB)
DATA go2xp_table+524(SB)/4, $0
// ws2_32.dll!WSAPoll
DATA go2xp_table+528(SB)/4, $go2xp_s_ws2_32_dll(SB)
DATA go2xp_table+532(SB)/4, $go2xp_s_WSAPoll(SB)
DATA go2xp_table+536(SB)/4, $·xp_WSAPoll(SB)
DATA go2xp_table+540(SB)/4, $0
// dwmapi.dll!DwmSetWindowAttribute
DATA go2xp_table+544(SB)/4, $go2xp_s_dwmapi_dll(SB)
DATA go2xp_table+548(SB)/4, $go2xp_s_DwmSetWindowAttribute(SB)
DATA go2xp_table+552(SB)/4, $·xp_DwmSetWindowAttribute(SB)
DATA go2xp_table+556(SB)/4, $0
// user32.dll!GetDpiForWindow
DATA go2xp_table+560(SB)/4, $go2xp_s_user32_dll(SB)
DATA go2xp_table+564(SB)/4, $go2xp_s_GetDpiForWindow(SB)
DATA go2xp_table+568(SB)/4, $·xp_GetDpiForWindow(SB)
DATA go2xp_table+572(SB)/4, $0
// user32.dll!SetProcessDpiAwarenessContext
DATA go2xp_table+576(SB)/4, $go2xp_s_user32_dll(SB)
DATA go2xp_table+580(SB)/4, $go2xp_s_SetProcessDpiAwarenessContext(SB)
DATA go2xp_table+584(SB)/4, $·xp_SetProcessDpiAwarenessContext(SB)
DATA go2xp_table+588(SB)/4, $0
// kernel32.dll!SetErrorMode
DATA go2xp_table+592(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+596(SB)/4, $go2xp_s_SetErrorMode(SB)
DATA go2xp_table+600(SB)/4, $0
DATA go2xp_table+604(SB)/4, $go2xp_SetErrorMode(SB)
// kernel32.dll!TerminateProcess
DATA go2xp_table+608(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+612(SB)/4, $go2xp_s_TerminateProcess(SB)
DATA go2xp_table+616(SB)/4, $0
DATA go2xp_table+620(SB)/4, $go2xp_TerminateProcess(SB)
// kernel32.dll!GetQueuedCompletionStatus
DATA go2xp_table+624(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+628(SB)/4, $go2xp_s_GetQueuedCompletionStatus(SB)
DATA go2xp_table+632(SB)/4, $0
DATA go2xp_table+636(SB)/4, $go2xp_GetQueuedCompletionStatus(SB)
// kernel32.dll!CancelIo
DATA go2xp_table+640(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+644(SB)/4, $go2xp_s_CancelIo(SB)
DATA go2xp_table+648(SB)/4, $0
DATA go2xp_table+652(SB)/4, $go2xp_CancelIo(SB)
// kernel32.dll!GetSystemDirectoryW
DATA go2xp_table+656(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+660(SB)/4, $go2xp_s_GetSystemDirectoryW(SB)
DATA go2xp_table+664(SB)/4, $0
DATA go2xp_table+668(SB)/4, $go2xp_GetSystemDirectoryW(SB)
// kernel32.dll!SetLastError
DATA go2xp_table+672(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+676(SB)/4, $go2xp_s_SetLastError(SB)
DATA go2xp_table+680(SB)/4, $0
DATA go2xp_table+684(SB)/4, $go2xp_SetLastError(SB)
// kernel32.dll!GetTickCount
DATA go2xp_table+688(SB)/4, $go2xp_s_kernel32_dll(SB)
DATA go2xp_table+692(SB)/4, $go2xp_s_GetTickCount(SB)
DATA go2xp_table+696(SB)/4, $0
DATA go2xp_table+700(SB)/4, $go2xp_GetTickCount(SB)
// advapi32.dll!SystemFunction036
DATA go2xp_table+704(SB)/4, $go2xp_s_advapi32_dll(SB)
DATA go2xp_table+708(SB)/4, $go2xp_s_SystemFunction036(SB)
DATA go2xp_table+712(SB)/4, $0
DATA go2xp_table+716(SB)/4, $go2xp_SystemFunction036(SB)
GLOBL go2xp_table(SB), NOPTR, $720
DATA go2xp_missing_dlls+0(SB)/4, $go2xp_s_bcryptprimitives_dll(SB)
DATA go2xp_missing_dlls+4(SB)/4, $0
GLOBL go2xp_missing_dlls(SB), RODATA|NOPTR, $8
DATA go2xp_overrides+0(SB)/4, $go2xp_s_WSASocketW(SB)
DATA go2xp_overrides+4(SB)/4, $go2xp_s_CreateProcessW(SB)
DATA go2xp_overrides+8(SB)/4, $go2xp_s_NtCreateFile(SB)
DATA go2xp_overrides+12(SB)/4, $0
GLOBL go2xp_overrides(SB), RODATA|NOPTR, $16
DATA go2xp_s_CancelIo+0(SB)/8, $"CancelIo"
DATA go2xp_s_CancelIo+8(SB)/8, $"\x00\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_CancelIo(SB), RODATA|NOPTR, $16
DATA go2xp_s_CancelIoEx+0(SB)/8, $"CancelIo"
DATA go2xp_s_CancelIoEx+8(SB)/8, $"Ex\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_CancelIoEx(SB), RODATA|NOPTR, $16
DATA go2xp_s_ClosePseudoConsole+0(SB)/8, $"ClosePse"
DATA go2xp_s_ClosePseudoConsole+8(SB)/8, $"udoConso"
DATA go2xp_s_ClosePseudoConsole+16(SB)/8, $"le\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ClosePseudoConsole(SB), RODATA|NOPTR, $24
DATA go2xp_s_CreateEventExW+0(SB)/8, $"CreateEv"
DATA go2xp_s_CreateEventExW+8(SB)/8, $"entExW\x00\x00"
GLOBL go2xp_s_CreateEventExW(SB), RODATA|NOPTR, $16
DATA go2xp_s_CreateProcessW+0(SB)/8, $"CreatePr"
DATA go2xp_s_CreateProcessW+8(SB)/8, $"ocessW\x00\x00"
GLOBL go2xp_s_CreateProcessW(SB), RODATA|NOPTR, $16
DATA go2xp_s_CreatePseudoConsole+0(SB)/8, $"CreatePs"
DATA go2xp_s_CreatePseudoConsole+8(SB)/8, $"eudoCons"
DATA go2xp_s_CreatePseudoConsole+16(SB)/8, $"ole\x00\x00\x00\x00\x00"
GLOBL go2xp_s_CreatePseudoConsole(SB), RODATA|NOPTR, $24
DATA go2xp_s_CreateSymbolicLinkW+0(SB)/8, $"CreateSy"
DATA go2xp_s_CreateSymbolicLinkW+8(SB)/8, $"mbolicLi"
DATA go2xp_s_CreateSymbolicLinkW+16(SB)/8, $"nkW\x00\x00\x00\x00\x00"
GLOBL go2xp_s_CreateSymbolicLinkW(SB), RODATA|NOPTR, $24
DATA go2xp_s_CreateWaitableTimerExW+0(SB)/8, $"CreateWa"
DATA go2xp_s_CreateWaitableTimerExW+8(SB)/8, $"itableTi"
DATA go2xp_s_CreateWaitableTimerExW+16(SB)/8, $"merExW\x00\x00"
GLOBL go2xp_s_CreateWaitableTimerExW(SB), RODATA|NOPTR, $24
DATA go2xp_s_DeleteProcThreadAttributeList+0(SB)/8, $"DeletePr"
DATA go2xp_s_DeleteProcThreadAttributeList+8(SB)/8, $"ocThread"
DATA go2xp_s_DeleteProcThreadAttributeList+16(SB)/8, $"Attribut"
DATA go2xp_s_DeleteProcThreadAttributeList+24(SB)/8, $"eList\x00\x00\x00"
GLOBL go2xp_s_DeleteProcThreadAttributeList(SB), RODATA|NOPTR, $32
DATA go2xp_s_DwmSetWindowAttribute+0(SB)/8, $"DwmSetWi"
DATA go2xp_s_DwmSetWindowAttribute+8(SB)/8, $"ndowAttr"
DATA go2xp_s_DwmSetWindowAttribute+16(SB)/8, $"ibute\x00\x00\x00"
GLOBL go2xp_s_DwmSetWindowAttribute(SB), RODATA|NOPTR, $24
DATA go2xp_s_FindFirstStreamW+0(SB)/8, $"FindFirs"
DATA go2xp_s_FindFirstStreamW+8(SB)/8, $"tStreamW"
DATA go2xp_s_FindFirstStreamW+16(SB)/8, $"\x00\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_FindFirstStreamW(SB), RODATA|NOPTR, $24
DATA go2xp_s_FindNextStreamW+0(SB)/8, $"FindNext"
DATA go2xp_s_FindNextStreamW+8(SB)/8, $"StreamW\x00"
GLOBL go2xp_s_FindNextStreamW(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetCurrentConsoleFontEx+0(SB)/8, $"GetCurre"
DATA go2xp_s_GetCurrentConsoleFontEx+8(SB)/8, $"ntConsol"
DATA go2xp_s_GetCurrentConsoleFontEx+16(SB)/8, $"eFontEx\x00"
GLOBL go2xp_s_GetCurrentConsoleFontEx(SB), RODATA|NOPTR, $24
DATA go2xp_s_GetDpiForWindow+0(SB)/8, $"GetDpiFo"
DATA go2xp_s_GetDpiForWindow+8(SB)/8, $"rWindow\x00"
GLOBL go2xp_s_GetDpiForWindow(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetErrorMode+0(SB)/8, $"GetError"
DATA go2xp_s_GetErrorMode+8(SB)/8, $"Mode\x00\x00\x00\x00"
GLOBL go2xp_s_GetErrorMode(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetFileInformationByHandleEx+0(SB)/8, $"GetFileI"
DATA go2xp_s_GetFileInformationByHandleEx+8(SB)/8, $"nformati"
DATA go2xp_s_GetFileInformationByHandleEx+16(SB)/8, $"onByHand"
DATA go2xp_s_GetFileInformationByHandleEx+24(SB)/8, $"leEx\x00\x00\x00\x00"
GLOBL go2xp_s_GetFileInformationByHandleEx(SB), RODATA|NOPTR, $32
DATA go2xp_s_GetFinalPathNameByHandleW+0(SB)/8, $"GetFinal"
DATA go2xp_s_GetFinalPathNameByHandleW+8(SB)/8, $"PathName"
DATA go2xp_s_GetFinalPathNameByHandleW+16(SB)/8, $"ByHandle"
DATA go2xp_s_GetFinalPathNameByHandleW+24(SB)/8, $"W\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_GetFinalPathNameByHandleW(SB), RODATA|NOPTR, $32
DATA go2xp_s_GetProcAddress+0(SB)/8, $"GetProcA"
DATA go2xp_s_GetProcAddress+8(SB)/8, $"ddress\x00\x00"
GLOBL go2xp_s_GetProcAddress(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetQueuedCompletionStatus+0(SB)/8, $"GetQueue"
DATA go2xp_s_GetQueuedCompletionStatus+8(SB)/8, $"dComplet"
DATA go2xp_s_GetQueuedCompletionStatus+16(SB)/8, $"ionStatu"
DATA go2xp_s_GetQueuedCompletionStatus+24(SB)/8, $"s\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_GetQueuedCompletionStatus(SB), RODATA|NOPTR, $32
DATA go2xp_s_GetQueuedCompletionStatusEx+0(SB)/8, $"GetQueue"
DATA go2xp_s_GetQueuedCompletionStatusEx+8(SB)/8, $"dComplet"
DATA go2xp_s_GetQueuedCompletionStatusEx+16(SB)/8, $"ionStatu"
DATA go2xp_s_GetQueuedCompletionStatusEx+24(SB)/8, $"sEx\x00\x00\x00\x00\x00"
GLOBL go2xp_s_GetQueuedCompletionStatusEx(SB), RODATA|NOPTR, $32
DATA go2xp_s_GetSystemDirectoryW+0(SB)/8, $"GetSyste"
DATA go2xp_s_GetSystemDirectoryW+8(SB)/8, $"mDirecto"
DATA go2xp_s_GetSystemDirectoryW+16(SB)/8, $"ryW\x00\x00\x00\x00\x00"
GLOBL go2xp_s_GetSystemDirectoryW(SB), RODATA|NOPTR, $24
DATA go2xp_s_GetTickCount+0(SB)/8, $"GetTickC"
DATA go2xp_s_GetTickCount+8(SB)/8, $"ount\x00\x00\x00\x00"
GLOBL go2xp_s_GetTickCount(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetTickCount64+0(SB)/8, $"GetTickC"
DATA go2xp_s_GetTickCount64+8(SB)/8, $"ount64\x00\x00"
GLOBL go2xp_s_GetTickCount64(SB), RODATA|NOPTR, $16
DATA go2xp_s_GetVolumeInformationByHandleW+0(SB)/8, $"GetVolum"
DATA go2xp_s_GetVolumeInformationByHandleW+8(SB)/8, $"eInforma"
DATA go2xp_s_GetVolumeInformationByHandleW+16(SB)/8, $"tionByHa"
DATA go2xp_s_GetVolumeInformationByHandleW+24(SB)/8, $"ndleW\x00\x00\x00"
GLOBL go2xp_s_GetVolumeInformationByHandleW(SB), RODATA|NOPTR, $32
DATA go2xp_s_InitializeProcThreadAttributeList+0(SB)/8, $"Initiali"
DATA go2xp_s_InitializeProcThreadAttributeList+8(SB)/8, $"zeProcTh"
DATA go2xp_s_InitializeProcThreadAttributeList+16(SB)/8, $"readAttr"
DATA go2xp_s_InitializeProcThreadAttributeList+24(SB)/8, $"ibuteLis"
DATA go2xp_s_InitializeProcThreadAttributeList+32(SB)/8, $"t\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_InitializeProcThreadAttributeList(SB), RODATA|NOPTR, $40
DATA go2xp_s_LoadLibraryExW+0(SB)/8, $"LoadLibr"
DATA go2xp_s_LoadLibraryExW+8(SB)/8, $"aryExW\x00\x00"
GLOBL go2xp_s_LoadLibraryExW(SB), RODATA|NOPTR, $16
DATA go2xp_s_NtCreateFile+0(SB)/8, $"NtCreate"
DATA go2xp_s_NtCreateFile+8(SB)/8, $"File\x00\x00\x00\x00"
GLOBL go2xp_s_NtCreateFile(SB), RODATA|NOPTR, $16
DATA go2xp_s_ProcessPrng+0(SB)/8, $"ProcessP"
DATA go2xp_s_ProcessPrng+8(SB)/8, $"rng\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ProcessPrng(SB), RODATA|NOPTR, $16
DATA go2xp_s_QueryFullProcessImageNameW+0(SB)/8, $"QueryFul"
DATA go2xp_s_QueryFullProcessImageNameW+8(SB)/8, $"lProcess"
DATA go2xp_s_QueryFullProcessImageNameW+16(SB)/8, $"ImageNam"
DATA go2xp_s_QueryFullProcessImageNameW+24(SB)/8, $"eW\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_QueryFullProcessImageNameW(SB), RODATA|NOPTR, $32
DATA go2xp_s_RaiseFailFastException+0(SB)/8, $"RaiseFai"
DATA go2xp_s_RaiseFailFastException+8(SB)/8, $"lFastExc"
DATA go2xp_s_RaiseFailFastException+16(SB)/8, $"eption\x00\x00"
GLOBL go2xp_s_RaiseFailFastException(SB), RODATA|NOPTR, $24
DATA go2xp_s_ReOpenFile+0(SB)/8, $"ReOpenFi"
DATA go2xp_s_ReOpenFile+8(SB)/8, $"le\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ReOpenFile(SB), RODATA|NOPTR, $16
DATA go2xp_s_RegLoadMUIStringW+0(SB)/8, $"RegLoadM"
DATA go2xp_s_RegLoadMUIStringW+8(SB)/8, $"UIString"
DATA go2xp_s_RegLoadMUIStringW+16(SB)/8, $"W\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_RegLoadMUIStringW(SB), RODATA|NOPTR, $24
DATA go2xp_s_ResizePseudoConsole+0(SB)/8, $"ResizePs"
DATA go2xp_s_ResizePseudoConsole+8(SB)/8, $"eudoCons"
DATA go2xp_s_ResizePseudoConsole+16(SB)/8, $"ole\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ResizePseudoConsole(SB), RODATA|NOPTR, $24
DATA go2xp_s_SetErrorMode+0(SB)/8, $"SetError"
DATA go2xp_s_SetErrorMode+8(SB)/8, $"Mode\x00\x00\x00\x00"
GLOBL go2xp_s_SetErrorMode(SB), RODATA|NOPTR, $16
DATA go2xp_s_SetFileInformationByHandle+0(SB)/8, $"SetFileI"
DATA go2xp_s_SetFileInformationByHandle+8(SB)/8, $"nformati"
DATA go2xp_s_SetFileInformationByHandle+16(SB)/8, $"onByHand"
DATA go2xp_s_SetFileInformationByHandle+24(SB)/8, $"le\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_SetFileInformationByHandle(SB), RODATA|NOPTR, $32
DATA go2xp_s_SetLastError+0(SB)/8, $"SetLastE"
DATA go2xp_s_SetLastError+8(SB)/8, $"rror\x00\x00\x00\x00"
GLOBL go2xp_s_SetLastError(SB), RODATA|NOPTR, $16
DATA go2xp_s_SetProcessDpiAwarenessContext+0(SB)/8, $"SetProce"
DATA go2xp_s_SetProcessDpiAwarenessContext+8(SB)/8, $"ssDpiAwa"
DATA go2xp_s_SetProcessDpiAwarenessContext+16(SB)/8, $"renessCo"
DATA go2xp_s_SetProcessDpiAwarenessContext+24(SB)/8, $"ntext\x00\x00\x00"
GLOBL go2xp_s_SetProcessDpiAwarenessContext(SB), RODATA|NOPTR, $32
DATA go2xp_s_SystemFunction036+0(SB)/8, $"SystemFu"
DATA go2xp_s_SystemFunction036+8(SB)/8, $"nction03"
DATA go2xp_s_SystemFunction036+16(SB)/8, $"6\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_SystemFunction036(SB), RODATA|NOPTR, $24
DATA go2xp_s_TerminateProcess+0(SB)/8, $"Terminat"
DATA go2xp_s_TerminateProcess+8(SB)/8, $"eProcess"
DATA go2xp_s_TerminateProcess+16(SB)/8, $"\x00\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_TerminateProcess(SB), RODATA|NOPTR, $24
DATA go2xp_s_UpdateProcThreadAttribute+0(SB)/8, $"UpdatePr"
DATA go2xp_s_UpdateProcThreadAttribute+8(SB)/8, $"ocThread"
DATA go2xp_s_UpdateProcThreadAttribute+16(SB)/8, $"Attribut"
DATA go2xp_s_UpdateProcThreadAttribute+24(SB)/8, $"e\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_UpdateProcThreadAttribute(SB), RODATA|NOPTR, $32
DATA go2xp_s_WSAPoll+0(SB)/8, $"WSAPoll\x00"
GLOBL go2xp_s_WSAPoll(SB), RODATA|NOPTR, $8
DATA go2xp_s_WSASocketW+0(SB)/8, $"WSASocke"
DATA go2xp_s_WSASocketW+8(SB)/8, $"tW\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_WSASocketW(SB), RODATA|NOPTR, $16
DATA go2xp_s_WerGetFlags+0(SB)/8, $"WerGetFl"
DATA go2xp_s_WerGetFlags+8(SB)/8, $"ags\x00\x00\x00\x00\x00"
GLOBL go2xp_s_WerGetFlags(SB), RODATA|NOPTR, $16
DATA go2xp_s_WerSetFlags+0(SB)/8, $"WerSetFl"
DATA go2xp_s_WerSetFlags+8(SB)/8, $"ags\x00\x00\x00\x00\x00"
GLOBL go2xp_s_WerSetFlags(SB), RODATA|NOPTR, $16
DATA go2xp_s_advapi32_dll+0(SB)/8, $"advapi32"
DATA go2xp_s_advapi32_dll+8(SB)/8, $".dll\x00\x00\x00\x00"
GLOBL go2xp_s_advapi32_dll(SB), RODATA|NOPTR, $16
DATA go2xp_s_bcryptprimitives_dll+0(SB)/8, $"bcryptpr"
DATA go2xp_s_bcryptprimitives_dll+8(SB)/8, $"imitives"
DATA go2xp_s_bcryptprimitives_dll+16(SB)/8, $".dll\x00\x00\x00\x00"
GLOBL go2xp_s_bcryptprimitives_dll(SB), RODATA|NOPTR, $24
DATA go2xp_s_dwmapi_dll+0(SB)/8, $"dwmapi.d"
DATA go2xp_s_dwmapi_dll+8(SB)/8, $"ll\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_dwmapi_dll(SB), RODATA|NOPTR, $16
DATA go2xp_s_kernel32_dll+0(SB)/8, $"kernel32"
DATA go2xp_s_kernel32_dll+8(SB)/8, $".dll\x00\x00\x00\x00"
GLOBL go2xp_s_kernel32_dll(SB), RODATA|NOPTR, $16
DATA go2xp_s_ntdll_dll+0(SB)/8, $"ntdll.dl"
DATA go2xp_s_ntdll_dll+8(SB)/8, $"l\x00\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ntdll_dll(SB), RODATA|NOPTR, $16
DATA go2xp_s_user32_dll+0(SB)/8, $"user32.d"
DATA go2xp_s_user32_dll+8(SB)/8, $"ll\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_user32_dll(SB), RODATA|NOPTR, $16
DATA go2xp_s_ws2_32_dll+0(SB)/8, $"ws2_32.d"
DATA go2xp_s_ws2_32_dll+8(SB)/8, $"ll\x00\x00\x00\x00\x00\x00"
GLOBL go2xp_s_ws2_32_dll(SB), RODATA|NOPTR, $16
// --- generated by gen_table.py: end ---

TEXT ·tableAddr(SB), NOSPLIT, $0-4
	LEAL	go2xp_table(SB), AX
	MOVL	AX, ret+0(FP)
	RET

// Load a missing DLL through the sentinel. For LOAD_LIBRARY_SEARCH_SYSTEM32,
// construct an absolute path before clearing unsupported XP search flags. Never
// fall back to a bare name when the directory query or bounded append fails.
TEXT ·xp_LoadLibraryExW(SB), NOSPLIT|NOFRAME, $0-0
	PUSHL SI
	PUSHL DI
	PUSHL BX
	SUBL $528, SP
	// return 540(SP), name 544(SP), hFile 548(SP), flags 552(SP)
	MOVL 544(SP), BX
	TESTL BX, BX
	JZ llx_bare
	LEAL go2xp_missing_dlls(SB), DX
llx_entry:
	MOVL (DX), DI
	TESTL DI, DI
	JZ llx_forward
	MOVL BX, SI
llx_cmp:
	MOVWLZX (SI), AX
	CMPL AX, $65
	JB llx_folded
	CMPL AX, $90
	JA llx_folded
	ADDL $32, AX
llx_folded:
	MOVBLZX (DI), CX
	CMPL AX, CX
	JNE llx_next
	TESTL AX, AX
	JZ llx_sentinel
	ADDL $2, SI
	INCL DI
	JMP llx_cmp
llx_next:
	ADDL $4, DX
	JMP llx_entry
llx_sentinel:
	MOVL SENTINEL, AX
	JMP llx_ret
llx_forward:
	MOVL 552(SP), AX
	TESTL $0x800, AX
	JZ llx_bare
	SUBL $8, SP
	LEAL 8(SP), AX
	MOVL AX, 0(SP)
	MOVL $264, 4(SP)
	MOVL go2xp_GetSystemDirectoryW(SB), AX
	CALL AX
	TESTL AX, AX
	JZ llx_ret
	CMPL AX, $260
	JAE llx_too_long
	LEAL (SP)(AX*2), DI
	MOVWLZX -2(DI), CX
	CMPL CX, $92
	JEQ llx_copy
	MOVW $92, (DI)
	ADDL $2, DI
llx_copy:
	MOVL BX, SI
llx_copy_loop:
	LEAL 528(SP), CX
	CMPL DI, CX
	JAE llx_too_long
	MOVWLZX (SI), AX
	CMPL AX, $92
	JEQ llx_bare
	CMPL AX, $47
	JEQ llx_bare
	CMPL AX, $58
	JEQ llx_bare
	MOVW AX, (DI)
	ADDL $2, SI
	ADDL $2, DI
	TESTL AX, AX
	JNZ llx_copy_loop
	MOVL SP, CX
	JMP llx_call
llx_too_long:
	SUBL $4, SP
	MOVL $206, 0(SP) // ERROR_FILENAME_EXCED_RANGE
	MOVL go2xp_SetLastError(SB), AX
	CALL AX
	XORL AX, AX
	JMP llx_ret
llx_bare:
	MOVL 544(SP), CX
llx_call:
	MOVL 552(SP), AX
	ANDL $0xFFFFE0FF, AX
	SUBL $12, SP
	MOVL AX, 8(SP)
	MOVL 560(SP), AX
	MOVL AX, 4(SP)
	MOVL CX, 0(SP)
	MOVL go2xp_LoadLibraryExW(SB), AX
	CALL AX
llx_ret:
	ADDL $528, SP
	POPL BX
	POPL DI
	POPL SI
	STDRET(12)

// FARPROC WINAPI GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
//
// This is the reason the whole design works with two slots: every lazily resolved import
// in the program - the runtime's own windowsFindfunc, syscall.GetProcAddress and
// therefore all of golang.org/x/sys/windows - funnels through here, so a polyfill in
// GO2XPTBL covers all of them at once, with no generated code to patch.
//
// The real function is asked first and always wins, so a polyfill is used only where the
// OS genuinely lacks the export. That keeps one patched binary correct across Windows
// versions: the same exe prefers the native CancelIoEx on Win7 and falls back to the
// CancelIo emulation on XP, with no profile involved at run time. The exception is the
// sentinel handle, which belongs to a DLL that is not there at all and can only be
// answered from the table.
//
// Two things reverse that order. A name in go2xp_overrides is answered from the table
// even though the OS has it: those are functions that exist on the target but reject an
// argument modern Go always passes (WSASocketW and its inheritance flag), so the wrapper
// has to sit in front of the real one. And setting forcePolyfills does it for every
// name the table knows. Anything the table does not know still goes to
// the real function - the point is to exercise the polyfills on a system that has the
// real ones, not to break every other lookup (see scripts/wine-test.sh).
TEXT ·xp_GetProcAddress(SB), NOSPLIT|NOFRAME, $0-0
	PUSHL	SI
	PUSHL	DI
	PUSHL	BX
	SUBL	$4, SP			// 0(SP): where a table miss should go next
	// return address at 16(SP); hModule 20(SP), lpProcName 24(SP)
	MOVL	$0, 0(SP)		// a miss fails, because the real call already ran
	MOVL	20(SP), AX
	CMPL	AX, SENTINEL
	JEQ	gpa_table		// a DLL that is not there: only the table can answer
	MOVL	·forcePolyfills(SB), AX
	TESTL	AX, AX
	JNZ	gpa_table_first
	MOVL	24(SP), BX
	CMPL	BX, $0x10000
	JB	gpa_real_first		// by ordinal: never an override
	LEAL	go2xp_overrides(SB), DX	// is this one of the names that need a wrapper?

gpa_ovr_entry:
	MOVL	(DX), DI
	TESTL	DI, DI
	JZ	gpa_real_first		// not an override: the real export wins
	MOVL	BX, SI

gpa_ovr_cmp:
	MOVBLZX	(DI), AX
	CMPB	(SI), AL
	JNE	gpa_ovr_next
	TESTL	AX, AX
	JZ	gpa_table_first		// matched: the table wins for this name
	INCL	SI
	INCL	DI
	JMP	gpa_ovr_cmp

gpa_ovr_next:
	ADDL	$4, DX
	JMP	gpa_ovr_entry

gpa_table_first:
	MOVL	$1, 0(SP)		// a miss still has to reach the real export
	JMP	gpa_table

gpa_real_first:
	SUBL	$8, SP
	MOVL	32(SP), AX		// lpProcName
	MOVL	AX, 4(SP)
	MOVL	28(SP), AX		// hModule
	MOVL	AX, 0(SP)
	MOVL	go2xp_GetProcAddress(SB), AX
	CALL	AX
	TESTL	AX, AX
	JNZ	gpa_ret			// it exists here: nothing to emulate

gpa_table:
	MOVL	24(SP), BX
	CMPL	BX, $0x10000		// imported by ordinal: nothing to match by name
	JB	gpa_miss
	LEAL	go2xp_table(SB), DX
	MOVL	12(DX), CX		// entry count
	ADDL	$16, DX			// first entry

gpa_entry:
	TESTL	CX, CX
	JZ	gpa_miss
	MOVL	8(DX), AX		// polyfill VA
	TESTL	AX, AX
	JZ	gpa_next		// own-slot-only entry, nothing to serve
	MOVL	4(DX), DI		// this entry's function name
	MOVL	BX, SI

gpa_cmp:
	MOVBLZX	(DI), AX
	CMPB	(SI), AL		// GetProcAddress is case-sensitive: compare exactly
	JNE	gpa_next
	TESTL	AX, AX
	JZ	gpa_hit
	INCL	SI
	INCL	DI
	JMP	gpa_cmp

gpa_next:
	ADDL	$16, DX
	DECL	CX
	JMP	gpa_entry

gpa_hit:
	MOVL	8(DX), AX
	JMP	gpa_ret

gpa_miss:
	MOVL	0(SP), AX
	TESTL	AX, AX
	JZ	gpa_fail
	SUBL	$8, SP			// forced mode: everything else is still the OS's job
	MOVL	32(SP), AX		// lpProcName
	MOVL	AX, 4(SP)
	MOVL	28(SP), AX		// hModule
	MOVL	AX, 0(SP)
	MOVL	go2xp_GetProcAddress(SB), AX
	CALL	AX
	JMP	gpa_ret

gpa_fail:
	SUBL $4, SP
	MOVL $127, 0(SP) // ERROR_PROC_NOT_FOUND, also for sentinel misses
	MOVL go2xp_SetLastError(SB), AX
	CALL AX
	XORL AX, AX

gpa_ret:
	ADDL	$4, SP
	POPL	BX
	POPL	DI
	POPL	SI
	STDRET(8)

// BOOL WINAPI GetQueuedCompletionStatusEx(HANDLE port, LPOVERLAPPED_ENTRY entries,
//     ULONG count, PULONG removed, DWORD timeout, BOOL alertable) - Vista+.
//
// The last static import the runtime needs that XP does not have. Emulated with plain
// GetQueuedCompletionStatus, which dequeues exactly one packet, so netpoll gets one entry
// per call instead of up to 64: slower under load, but not different in behaviour.
//
// The three outcomes are kept faithful. A dequeued packet fills entries[0] and returns
// TRUE. A timeout returns FALSE with the last error already set to WAIT_TIMEOUT, which is
// what netpoll checks for. A packet belonging to a failed I/O makes the plain function
// return FALSE with a non-NULL OVERLAPPED, and the Ex form reports that as a normal
// dequeue, so it is turned back into TRUE here; the status stays in the OVERLAPPED where
// the caller reads it from. fAlertable has no equivalent and is ignored (the runtime
// always passes FALSE).
TEXT ·xp_GetQueuedCompletionStatusEx(SB), NOSPLIT|NOFRAME, $0-0
	PUSHL	BX
	PUSHL	SI
	PUSHL	DI
	// return address at 12(SP); port 16, entries 20, count 24, removed 28, timeout 32
	MOVL	24(SP), AX
	TESTL	AX, AX
	JZ	gqe_fail		// no room for even one entry
	SUBL	$12, SP			// scratch: bytes 0(SP), key 4(SP), overlapped 8(SP)
	MOVL	$0, 8(SP)
	SUBL	$20, SP			// arguments for GetQueuedCompletionStatus
	MOVL	48(SP), AX		// port
	MOVL	AX, 0(SP)
	LEAL	20(SP), AX		// &bytes
	MOVL	AX, 4(SP)
	LEAL	24(SP), AX		// &key
	MOVL	AX, 8(SP)
	LEAL	28(SP), AX		// &overlapped
	MOVL	AX, 12(SP)
	MOVL	64(SP), AX		// timeout
	MOVL	AX, 16(SP)
	MOVL	go2xp_GetQueuedCompletionStatus(SB), AX
	CALL	AX			// callee pops 20; scratch is at 0/4/8(SP) again
	TESTL	AX, AX
	JNZ	gqe_fill
	MOVL	8(SP), AX		// FALSE: was a packet still dequeued?
	TESTL	AX, AX
	JZ	gqe_unwind		// no - timeout or a real error, propagate it

gqe_fill:
	MOVL	32(SP), DI		// entries
	MOVL	4(SP), AX		// lpCompletionKey
	MOVL	AX, 0(DI)
	MOVL	8(SP), AX		// lpOverlapped
	MOVL	AX, 4(DI)
	MOVL	$0, 8(DI)		// Internal
	MOVL	0(SP), AX		// dwNumberOfBytesTransferred
	MOVL	AX, 12(DI)
	MOVL	40(SP), DI		// removed
	MOVL	$1, (DI)
	ADDL	$12, SP
	MOVL	$1, AX
	JMP	gqe_ret

gqe_unwind:
	ADDL	$12, SP

gqe_fail:
	XORL	AX, AX

gqe_ret:
	POPL	DI
	POPL	SI
	POPL	BX
	STDRET(24)

// BOOL WINAPI ProcessPrng(PBYTE pbData, SIZE_T cbData) - Win10+, bcryptprimitives.dll.
// XP's equivalent is advapi32!SystemFunction036, better known as RtlGenRandom: same
// argument layout, same cryptographic role, present since XP SP1. It returns BOOLEAN in
// AL, so the result is zero-extended before it becomes the BOOL the runtime tests.
TEXT ·xp_ProcessPrng(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$8, SP
	MOVL	16(SP), AX		// cbData
	MOVL	AX, 4(SP)
	MOVL	12(SP), AX		// pbData
	MOVL	AX, 0(SP)
	MOVL	go2xp_SystemFunction036(SB), AX
	CALL	AX
	MOVBLZX	AL, AX
	STDRET(8)

// HRESULT WINAPI WerSetFlags(DWORD dwFlags) - Vista+.
// Windows Error Reporting only affects crash dialogs, so a no-op returning S_OK is
// enough: runtime.preventErrorDialogs also calls SetErrorMode, which XP has.
TEXT ·xp_WerSetFlags(SB), NOSPLIT|NOFRAME, $0-0
	XORL	AX, AX
	STDRET(4)

// HRESULT WINAPI WerGetFlags(HANDLE hProcess, PDWORD pdwFlags) - Vista+.
// Reports "no flags set" so that the WerSetFlags call that follows is a no-op too.
TEXT ·xp_WerGetFlags(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	8(SP), AX		// pdwFlags
	TESTL	AX, AX
	JZ	wgf_done
	MOVL	$0, (AX)
wgf_done:
	XORL	AX, AX
	STDRET(8)

// UINT WINAPI GetErrorMode(void) - Vista+.
// XP has no getter, but SetErrorMode returns the previous mode, so set-and-restore
// recovers it. This races with a concurrent SetErrorMode, which is acceptable here: the
// runtime calls it once from preventErrorDialogs during osinit.
TEXT ·xp_GetErrorMode(SB), NOSPLIT|NOFRAME, $0-0
	PUSHL	BX
	SUBL	$4, SP
	MOVL	$0, 0(SP)
	MOVL	go2xp_SetErrorMode(SB), AX
	CALL	AX
	MOVL	AX, BX			// BX = previous mode
	SUBL	$4, SP
	MOVL	BX, 0(SP)
	MOVL	go2xp_SetErrorMode(SB), AX
	CALL	AX			// put it back
	MOVL	BX, AX
	POPL	BX
	RET

// HANDLE WINAPI CreateWaitableTimerExW(LPSECURITY_ATTRIBUTES, LPCWSTR, DWORD, DWORD) - Vista+.
// Returning NULL is a supported outcome for runtime.initHighResTimer: it clears
// haveHighResTimer and the runtime falls back to winmm timeBeginPeriod, which is exactly
// the pre-1.23 behaviour and works on XP.
TEXT ·xp_CreateWaitableTimerExW(SB), NOSPLIT|NOFRAME, $0-0
	XORL	AX, AX
	STDRET(16)

// VOID WINAPI RaiseFailFastException(PEXCEPTION_RECORD, PCONTEXT, DWORD) - Win7+.
// Fail-fast means "die now, no handlers, no debugger dialog". TerminateProcess on the
// current-process pseudo-handle is the closest XP equivalent; the exit code is
// STATUS_FAIL_FAST_EXCEPTION so crash reports still look the same. Never returns.
TEXT ·xp_RaiseFailFastException(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$8, SP
	MOVL	$-1, 0(SP)		// GetCurrentProcess() pseudo-handle
	MOVL	$0xC0000409, 4(SP)	// STATUS_FAIL_FAST_EXCEPTION
	MOVL	go2xp_TerminateProcess(SB), AX
	CALL	AX
	INT	$3			// unreachable
	STDRET(12)

// ULONGLONG WINAPI GetTickCount64(void) - Vista+.
// The 32-bit GetTickCount, zero-extended into EDX:EAX. It wraps every 49.7 days where the
// real one does not; nothing in Go's standard library calls this, so the compromise only
// reaches third-party code that asked for it explicitly.
TEXT ·xp_GetTickCount64(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	go2xp_GetTickCount(SB), AX
	CALL	AX
	XORL	DX, DX
	RET

// --- generated trampolines: begin ---
// CancelIoEx: stdcall callback, available after shim.init.
TEXT ·xp_CancelIoEx(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbCancelIoEx(SB), AX
	TESTL	AX, AX
	JZ	t_CancelIoEx_early
	JMP	AX
t_CancelIoEx_early:
	XORL	AX, AX
	STDRET(8)

// GetFileInformationByHandleEx: stdcall callback, available after shim.init.
TEXT ·xp_GetFileInformationByHandleEx(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbGetFileInformationByHandleEx(SB), AX
	TESTL	AX, AX
	JZ	t_GetFileInformationByHandleEx_early
	JMP	AX
t_GetFileInformationByHandleEx_early:
	XORL	AX, AX
	STDRET(16)

// SetFileInformationByHandle: stdcall callback, available after shim.init.
TEXT ·xp_SetFileInformationByHandle(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbSetFileInformationByHandle(SB), AX
	TESTL	AX, AX
	JZ	t_SetFileInformationByHandle_early
	JMP	AX
t_SetFileInformationByHandle_early:
	XORL	AX, AX
	STDRET(16)

// InitializeProcThreadAttributeList: stdcall callback, available after shim.init.
TEXT ·xp_InitializeProcThreadAttributeList(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbInitializeProcThreadAttributeList(SB), AX
	TESTL	AX, AX
	JZ	t_InitializeProcThreadAttributeList_early
	JMP	AX
t_InitializeProcThreadAttributeList_early:
	XORL	AX, AX
	STDRET(16)

// UpdateProcThreadAttribute: stdcall callback, available after shim.init.
TEXT ·xp_UpdateProcThreadAttribute(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbUpdateProcThreadAttribute(SB), AX
	TESTL	AX, AX
	JZ	t_UpdateProcThreadAttribute_early
	JMP	AX
t_UpdateProcThreadAttribute_early:
	XORL	AX, AX
	STDRET(28)

// DeleteProcThreadAttributeList: stdcall callback, available after shim.init.
TEXT ·xp_DeleteProcThreadAttributeList(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbDeleteProcThreadAttributeList(SB), AX
	TESTL	AX, AX
	JZ	t_DeleteProcThreadAttributeList_early
	JMP	AX
t_DeleteProcThreadAttributeList_early:
	XORL	AX, AX
	STDRET(4)

// WSASocketW: stdcall callback, available after shim.init.
TEXT ·xp_WSASocketW(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbWSASocketW(SB), AX
	TESTL	AX, AX
	JZ	t_WSASocketW_early
	JMP	AX
t_WSASocketW_early:
	XORL	AX, AX
	STDRET(24)

// CreateEventExW: stdcall callback, available after shim.init.
TEXT ·xp_CreateEventExW(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbCreateEventExW(SB), AX
	TESTL	AX, AX
	JZ	t_CreateEventExW_early
	JMP	AX
t_CreateEventExW_early:
	XORL	AX, AX
	STDRET(16)

// CreateProcessW: stdcall callback, available after shim.init.
TEXT ·xp_CreateProcessW(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbCreateProcessW(SB), AX
	TESTL	AX, AX
	JZ	t_CreateProcessW_early
	JMP	AX
t_CreateProcessW_early:
	XORL	AX, AX
	STDRET(40)

// NtCreateFile: stdcall callback, available after shim.init.
TEXT ·xp_NtCreateFile(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbNtCreateFile(SB), AX
	TESTL	AX, AX
	JZ	t_NtCreateFile_early
	JMP	AX
t_NtCreateFile_early:
	XORL	AX, AX
	STDRET(44)

// GetVolumeInformationByHandleW: stdcall callback, available after shim.init.
TEXT ·xp_GetVolumeInformationByHandleW(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·cbGetVolumeInformationByHandleW(SB), AX
	TESTL	AX, AX
	JZ	t_GetVolumeInformationByHandleW_early
	JMP	AX
t_GetVolumeInformationByHandleW_early:
	XORL	AX, AX
	STDRET(32)

// kernel32.dll!GetFinalPathNameByHandleW: absent on the target, no polyfill. Returns 0, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_GetFinalPathNameByHandleW(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(16)

// kernel32.dll!CreateSymbolicLinkW: absent on the target, no polyfill. Returns 0, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_CreateSymbolicLinkW(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(12)

// kernel32.dll!ReOpenFile: absent on the target, no polyfill. Returns -1, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_ReOpenFile(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$-1, AX
	STDRET(16)

// kernel32.dll!QueryFullProcessImageNameW: absent on the target, no polyfill. Returns 0, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_QueryFullProcessImageNameW(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(16)

// kernel32.dll!GetCurrentConsoleFontEx: absent on the target, no polyfill. Returns 0, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_GetCurrentConsoleFontEx(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(12)

// kernel32.dll!FindFirstStreamW: absent on the target, no polyfill. Returns -1, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_FindFirstStreamW(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$-1, AX
	STDRET(16)

// kernel32.dll!FindNextStreamW: absent on the target, no polyfill. Returns 0, last error 18
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_FindNextStreamW(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$18, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(8)

// kernel32.dll!CreatePseudoConsole: absent on the target, no polyfill. Returns 2147500033
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_CreatePseudoConsole(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$2147500033, AX
	STDRET(20)

// kernel32.dll!ResizePseudoConsole: absent on the target, no polyfill. Returns 2147500033
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_ResizePseudoConsole(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$2147500033, AX
	STDRET(8)

// kernel32.dll!ClosePseudoConsole: absent on the target, no polyfill. Returns 0
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_ClosePseudoConsole(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$0, AX
	STDRET(4)

// advapi32.dll!RegLoadMUIStringW: absent on the target, no polyfill. Returns 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_RegLoadMUIStringW(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$120, AX
	STDRET(28)

// ws2_32.dll!WSAPoll: absent on the target, no polyfill. Returns -1
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_WSAPoll(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	·wsaSetLastError(SB), AX
	TESTL	AX, AX
	JZ	s_WSAPoll_ret
	SUBL	$4, SP
	MOVL	$10045, 0(SP)
	CALL	AX
s_WSAPoll_ret:
	MOVL	$-1, AX
	STDRET(12)

// dwmapi.dll!DwmSetWindowAttribute: absent on the target, no polyfill. Returns 2147500033
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_DwmSetWindowAttribute(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$2147500033, AX
	STDRET(16)

// user32.dll!GetDpiForWindow: absent on the target, no polyfill. Returns 96
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_GetDpiForWindow(SB), NOSPLIT|NOFRAME, $0-0
	MOVL	$96, AX
	STDRET(4)

// user32.dll!SetProcessDpiAwarenessContext: absent on the target, no polyfill. Returns 0, last error 120
// so the caller sees an ordinary failure instead of the panic an unresolved LazyProc raises.
TEXT ·xp_SetProcessDpiAwarenessContext(SB), NOSPLIT|NOFRAME, $0-0
	SUBL	$4, SP
	MOVL	$120, 0(SP)
	MOVL	go2xp_SetLastError(SB), AX
	CALL	AX
	MOVL	$0, AX
	STDRET(4)

// --- generated trampolines: end ---
